# h6 django

## Rauta, jolla tehtävät suoritetaan: 
* CPU: AMD Ryzen 9 5900x 12-core 3700MHz, boost 4950 MHz
* Muisti: 32 GB, 4 x 8G GSkill DDR4 3200c14
* Emolevy: ASUS ROG STRIX X570-E GAMING
* GPU: ASUS ROG STRIX RTX 2070 OC
* CPU & GPU jäähdytetty vedellä 
* OS: Windows 11, version 23H2
* VMware - Debian 12.6.0

### a) Django esimerkkiohjelma

Tätä tehtävää varten asensin virtuaaliympäristön Debianin sisälle seuraten Teron esimerkkiä (Django 4 Instant Customer Database Tutorial, Karvinen Tero. https://terokarvinen.com/2022/django-instant-crm-tutorial/). Perinteiseen tapaan hain ensin päivitykset komennolla `sudo apt-get update`. Tämän jälkeen lähdin asentamaan virtuaaliympäristöä:

![Screenshot 2024-09-30 180354](https://github.com/user-attachments/assets/17f2b4dc-0d05-40fc-9a7a-23f480f3515d)

![Screenshot 2024-09-30 180425](https://github.com/user-attachments/assets/4ae1cb71-e7ec-41e0-92d4-b93f0834eb81)

Kun virtuaaliympäristö on saatu asennettua, aktivoin sen:

![Screenshot 2024-09-30 180443](https://github.com/user-attachments/assets/f6359434-c52e-4470-99cd-2256261ab8c5)

Jonka jälkeen tarkistin, että virtuaaliympäristö oli aktiivinen:

![Screenshot 2024-09-30 180443](https://github.com/user-attachments/assets/cca65ee1-f239-459e-8e10-73fdf86ac206)

Jonka jälkeen asensin micro editorin ja sen jälkeen loin uuden tekstitiedoston, jonka sisältönä oli "django"

![Screenshot 2024-09-30 180457](https://github.com/user-attachments/assets/4af1fcd0-cb9b-4629-9451-2228f2864422)

![Screenshot 2024-09-30 180518](https://github.com/user-attachments/assets/24a89986-ce34-4b59-ba34-4465adf1b018)

Tämän jälkeen asensin djangon sekä tarkistetin vielä mikä versio asentui. Omassa tapauksessa versio oli 5.1.1, joka pikaisen googletuksen perusteella on viimeisin.

![Screenshot 2024-09-30 180535](https://github.com/user-attachments/assets/f86a3f8d-cebd-426e-9db5-eb76ccb942af)

Seuraavan oli vuorossa yksinkertainen ohjelma djangolla, edelleen Teron ohjeiden mukaisesti. Aloitetaan uusi projekti ja käynnistetään se:

![image](https://github.com/user-attachments/assets/4b35cb70-de0f-4f5b-8698-1c71c40a4d37)

Käynnistyksen yhteydessä pisti silmään punainen teksti, että projektista puuttuu vielä oleellisia osia. Pikainen vilaisu Teron ohjeeseen ja niiden lisääminen on seuraavana vuorossa, joten ei paniikkia tässä vaiheessa. 

Tämän jälkeen kokeillin, onko virtuaaliserveri käynnissä suuntaaamalla selaimella osoitteeseen `http://127.0.0.1:8000`

![image](https://github.com/user-attachments/assets/c366700b-de53-487c-bd24-445d8c2d29c7)

Seuraavaksi tosiaan lisätään admin käyttäjä sekä kirjautumis näkymä:

![image](https://github.com/user-attachments/assets/70613762-a755-4b47-b471-05b270165092)

![image](https://github.com/user-attachments/assets/6f1517b9-e261-4ad9-b6aa-711a09a24fb6)

Tämän jälkeen kokeilemaan, toimiiko admin tunnarit, suuntaamalla selaimella osoitteeseen `http://127.0.0.1:8000/admin/` ja kokeillin kirjautusmista juuri luoduilla tunnuksilla.

![image](https://github.com/user-attachments/assets/d98e810d-1c11-48d0-a913-a92e0b4def9e)

Tämän jälkeen kokeilin luoda uuden käyttäjän webbiliittymän kautta, sekä varmistin, että luotu tunnus toimii:

![image](https://github.com/user-attachments/assets/609b0578-f7c7-4b8b-9e94-9a11762493e5)

Seuraavaksi lisäsin kansion crm/ sekä lisäsin asetuksiem asennettuihin ohjelmiin "crm"

![image](https://github.com/user-attachments/assets/a6623bda-2f9b-4c99-a20d-b8cd1643e6c5)

![image](https://github.com/user-attachments/assets/b67eca23-d76d-43e0-bb2e-d962f00e7909)

Seuraavaksi tuodaan malleja ohjelmaan komennolla `micro crm/models.py`:

![Screenshot 2024-09-30 185642](https://github.com/user-attachments/assets/a07c5949-aacb-4edd-a646-315dceba2552)

jonka jälkeen ajetaan migraatio:

![Screenshot 2024-09-30 185852](https://github.com/user-attachments/assets/153a6da5-a4cb-4b59-9150-a2b8ff40d484)

Logiin ilmeistyi virhe ilmoitus, joka viittaa äsken muokattuun tiedostoon ja kirjoitusvirheeseen:

![Screenshot 2024-09-30 185852](https://github.com/user-attachments/assets/6ab79ba1-715a-457c-a664-845782c974fa)

Joten korjataan virhe:

![image](https://github.com/user-attachments/assets/3e22d0a0-3cb7-43c6-93ee-437c6635af4a)

Jonka jälkeen ajoin migraation ja jälleen ilmoitus kirjoitusvirheesta, tällä kertaa kohdassa (max_lenght=200), joten krojaamaan jälleen:

![image](https://github.com/user-attachments/assets/862666b4-c5dc-4f3b-b445-25f69efb2f1b)

Ja jälleen koitin migraatiota ja tällä kertaa onnistunut lopputulos:

![image](https://github.com/user-attachments/assets/56615b45-6124-4a2a-bd99-e02190014935)

Seuraavaksi luotu tietokanta tulee rekisteröidä, jotta näemmä sen käyttöliittymässä. Tämä toteutaan komennolla `micro crm/admin.py`:

![image](https://github.com/user-attachments/assets/deb63d91-166e-49f2-a6dc-0a9e20373ebe)

Seuraavaksi kokeilin käynnistää serverin komennolla `./manage.py runserver`
Kuten tarkkasilmäiset ehkä huomasivat, oli admin.py tiedostossa jälleen kirjoitusvirhe ja tästä tuli virheilmoitus:

![image](https://github.com/user-attachments/assets/53f24548-e1f7-4fc5-9b81-1e77712a79df)

Joten korjasin virheet:

![image](https://github.com/user-attachments/assets/696cedcb-874c-4d0d-b5cd-57ac76e9320b)

Korjauksen jälkeen käynnistin serverin:

![image](https://github.com/user-attachments/assets/caa83662-5e01-4ed4-babd-69742489a46b)

Ja koska serveri käynnistyi ilman virheilmoituksia, seuraavaksi admin paneeliin katsastamaan, oliko näkymä muuttunut ja olihan se:

![image](https://github.com/user-attachments/assets/604e6963-245d-4449-941f-718c22afeff9)

Tämän jälkeen loin pari käyttäjää tietokantaan:

![image](https://github.com/user-attachments/assets/9bc666e4-a745-4a59-b583-78e8e09780b4)

![Screenshot 2024-09-30 192056](https://github.com/user-attachments/assets/74167628-d083-4995-91b8-d10505968ad7)

Jotta listasta olisi jotain hyötyä, olisi fiksua, että nimet näkyisivät suoraan listassa, eikä vain numeroina (Customer object (1)), joten muokataan models.py tiedostoa komennolla `micro crm/models.py` ja listään rivit 8 ja 9:

![image](https://github.com/user-attachments/assets/fae1c31c-d64b-436a-b942-825f788d4050)

Jonka jälkeen tarkistamaan, muuttuiko näkymä:

![image](https://github.com/user-attachments/assets/16c1f078-daae-4ae4-9f40-a06530f91a8f)

Tässä tehtävässä käytiin läpi yksinkertaisen ohjelman tekeminen djangolla ja sille luotiin vielä yksinkertainen paikallinen tietokanta. Tässä on hyvä huomioida, että kyseinen ohjelma näkyy vain admin paneelin kautta, ja on myös täkreää muistaa, että kehitysvaiheessa olevaa ohjelmistoa ei pidä koskaan laittaa julkisesti internettiin.

### b, c ja d) Tuotantotyyppinen asennus

Jotta saisin tehtävstä mahdollisimman paljon irti, päätin kokeilla tehdä django ohjelmiston tuotantotyyppisenä vuokraamalleni palvelimelle. Joten aluksi otin yhteyden etäpalvelimeeni ssh:lla ja päivitin sen komennolla `sudo apt-get update`. Tämän jälkeen asensin virtuaaliympäristön komennolla `sudo apt-get -y install virtualenv`, jonka jälkeen loin public kansioon vielä alikansiot komennolla `mkdir webapp/testapp` tulevalle django ohjelmistolle. 

Tässä välissä kävin tekemässä domainiini webapp sup-domainin:

![image](https://github.com/user-attachments/assets/03d62ea8-7d6b-416c-81bf-b080eba16be5)

Tämän jälkeen muokkasin Apache conffia komennolla `sudoedit /etc/apache2/sites-available/webapp.conf`

![image](https://github.com/user-attachments/assets/413c025d-97ae-4c68-a39e-124418994ddc)

Ja seuraavaksi enabloin äskeisen konffin sekä käynnistin apachen uudestaan:

![image](https://github.com/user-attachments/assets/be3df3e3-218b-4341-8877-6142f253b80b)

Seuraavaksi loin `index.html` tiedoston kansioon `webapp/testapp/` ja tämän jälkeen koikeilin komennolla `curl http://localhost/webapp/` ja sain tuloksesksi "403 Forbidden"

![Screenshot 2024-10-01 153930](https://github.com/user-attachments/assets/460d6b86-ebd6-4baa-a72e-dbf5d8bffbfe)

Jostain syystä ei ole pääsyä kyseiseen osoitteeseen, joten ensimmäisenä tarkistin oikeudet kansiossa `testapp/` ja selvisi, että `index.html` puuttuu tarvittavia oikeuksia.

![image](https://github.com/user-attachments/assets/bde13b44-1b3d-4fbb-92d6-3f68f5d7b842)

Seuraavaksi korjasin oikeudet tiedostolle:

![image](https://github.com/user-attachments/assets/7dfcef88-2363-46ff-80f7-6c5b25d36647)

Jonka jälkeen jälleen ajoin komennon `curl http://localhost/webapp/`, mutta tulos oli edelleen 403. Seuraavaksi tutkimaan apachen logeja. Access logissa näkyy 403

![image](https://github.com/user-attachments/assets/0ee7fe5b-d71b-4b61-b8c1-7a7c0b4c9a7d)

Seuraavaksi otin suurennuslasin alle error login ja sieltä syy löytyikin. Jostain syystä yrittää hakea väärän polun takaa tuota `http://localhost/webapp/` osoitetta. Polun pitäisi olla `/home/blop/public/webapp/testapp/` eikä `/home/blop/public/portfolio/webapp/`, josta se nyt yrittää hakea.

![image](https://github.com/user-attachments/assets/209d68f9-d7e9-45f2-91d1-18e59e6427a4)

Apachen default konfissa `sudoedit /etc/apache2/sites-available/000-default.conf` oli DocumentRoot kohdassa `/home/blop/public/portfolio/`, joten epäilen, että se haki tuolta kyseistä polkua. Muutin sen muotoon:

![image](https://github.com/user-attachments/assets/67d6bdc9-313e-4d8c-8a9d-8884d6ce492f)

Edelleen saan 403 forbidden, joten error logia tutkimaan ja nyt polku on jo mlekein oikein...

![image](https://github.com/user-attachments/assets/b0c2baad-438f-45b0-8375-51425e8b6040)

Jostain syystä ei hae /webapp/testapp/ kansiosta, joten kokeilen siirtää index.html askelta ylemmäs tuohon webapp kansioon. Tämän jälkeen korjasin vielä webapp.conffia, eli poistin sieltä tuon testapp/ kansion poluista. Apachen restartti varmuuden vuoksi, mutta edelleen saan 403 fobidden. 

## Lähteet


 * Karvinen, Tero. Linux palvelimet 2024 alkusyksy. https://terokarvinen.com/linux-palvelimet/
 * Karvinem, Tero. Django 4 Instant Customer Database Tutorial. https://terokarvinen.com/2022/django-instant-crm-tutorial/
 * 

